// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALZcizyCWi4u3woR7I-J-PbOj5Sn8qiko',
    appId: '1:582346892617:web:a7daab297393ae9018a698',
    messagingSenderId: '582346892617',
    projectId: 'fundlinker-a7fcb',
    authDomain: 'fundlinker-a7fcb.firebaseapp.com',
    storageBucket: 'fundlinker-a7fcb.appspot.com',
    measurementId: 'G-LF4DTD3XPN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcxpAWQLHf5E_O12X6S5eakTiwjxp6fbo',
    appId: '1:582346892617:android:7f138f63134450b618a698',
    messagingSenderId: '582346892617',
    projectId: 'fundlinker-a7fcb',
    storageBucket: 'fundlinker-a7fcb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC97sf7jNjb9TQSDLBwKTjrT2lV6cY6raY',
    appId: '1:582346892617:ios:66c4e2259fabd11d18a698',
    messagingSenderId: '582346892617',
    projectId: 'fundlinker-a7fcb',
    storageBucket: 'fundlinker-a7fcb.appspot.com',
    androidClientId: '582346892617-ip1aka0nfmfjl64dndv622a7v3e5c80p.apps.googleusercontent.com',
    iosClientId: '582346892617-u52861ugi3ri03tikcughg2344g4rmqg.apps.googleusercontent.com',
    iosBundleId: 'com.example.fundlinker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC97sf7jNjb9TQSDLBwKTjrT2lV6cY6raY',
    appId: '1:582346892617:ios:adfce247591f934418a698',
    messagingSenderId: '582346892617',
    projectId: 'fundlinker-a7fcb',
    storageBucket: 'fundlinker-a7fcb.appspot.com',
    androidClientId: '582346892617-ip1aka0nfmfjl64dndv622a7v3e5c80p.apps.googleusercontent.com',
    iosClientId: '582346892617-huojrs2f3l2m6rdsmmfolai5p5qsgbk0.apps.googleusercontent.com',
    iosBundleId: 'com.example.fundlinker.RunnerTests',
  );
}
